# Generated by Django 5.0.6 on 2024-06-19 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flights',
            name='airline',
        ),
    ]
