# Generated by Django 5.0.6 on 2024-06-23 18:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_sharedtrip_delete_airlines'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedtrip',
            name='arrival',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sharedtrip',
            name='departure',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sharedtrip',
            name='from_location',
            field=models.CharField(max_length=255, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sharedtrip',
            name='to_location',
            field=models.CharField(max_length=255, default=''),
            preserve_default=False,
        ),
    ]
